---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[code_deploy]
  - name: uninstall
    run_list:
      - recipe[code_deploy]
      - recipe[code_deploy_test::uninstall_agent]

verifier:
  name: inspec
