sudo: required
language: ruby
rvm:
- 2.3.1
services:
- docker
script:
- KITCHEN_YAML=.kitchen.docker.yml bundle exec kitchen test $SUITE
deploy:
  provider: script
  script: openssl aes-256-cbc -K $encrypted_ecb18825a7dd_key -iv $encrypted_ecb18825a7dd_iv -in .supermarket.pem.enc -out .supermarket.pem -d && rvm $TRAVIS_RUBY_VERSION do bundle exec stove login --username meringu --key .supermarket.pem && rvm $TRAVIS_RUBY_VERSION do bundle exec stove --no-git
  on:
    tags: true
env:
  - SUITE=install-centos-72
  - SUITE=install-ubuntu-1404
  - SUITE=install-and-start-centos-72
  # TODO: These two tests fail on travis
  # - SUITE=install-and-start-ubuntu-1404
  - SUITE=uninstall-centos-72
  # - SUITE=uninstall-ubuntu-1404
  - SUITE=reinstall-centos-72
  - SUITE=reinstall-ubuntu-1404
