sudo: required
language: ruby
services:
- docker
script:
- KITCHEN_YAML=.kitchen.docker.yml bundle exec kitchen test
deploy:
  provider: script
  script: openssl aes-256-cbc -K $encrypted_ecb18825a7dd_key -iv $encrypted_ecb18825a7dd_iv -in .supermarket.pem.enc -out .supermarket.pem -d && rvm $TRAVIS_RUBY_VERSION do bundle exec stove login --username meringu --key .supermarket.pem && rvm $TRAVIS_RUBY_VERSION do bundle exec stove --no-git
  on:
    tags: true
